name: Deploy API to Fly
on: 
  push:
    paths:
      - '**'
      - '.github/workflows/s3.yml'
  pull_request:
jobs:
  deploy:
    name: Deploy to S3
    runs-on: ubuntu-latest
    defaults:
      run:
        # ./ is the repo root
        working-directory: source/landing
    steps:
      # This step checks out a copy of your repository.
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: .
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-
      - uses: Amadevus/pwsh-script@v2
      - run: pwsh ./make.ps1
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
          FITEDIT_LANDING_CLOUDFRONT_DISTRIBUTIONID: ${{ secrets.FITEDIT_LANDING_CLOUDFRONT_DISTRIBUTIONID }}
          FITEDIT_LANDING_S3_BUCKET: ${{ secrets.FITEDIT_LANDING_S3_BUCKET }}
